### PR TITLE
Do something

### PR DESCRIPTION
**Pull request by ikornaselur**
- Add JSHint to gulp watch
- Split game into modules
- Add movement to the ball.
- Implement basic collision detection. Angle doesn't matter at the moment
- Add bricks
- Probably something else

Known "issues":
- Ball collision doesn't check if it's hitting the sides of an object (like the bricks), currently it will just reverse the `y` direction when it collides with something

To do:
- Scoring?
- Add lives?
- Winning screen?

breakout3

@DeadpoolAndObjectOrientedProgramming/owners

### CODE REVIEW

**Comment by koddsson** [comment]
Whoo! LGTM :tada:

**Comment by koddsson** [comment]
Maybe you can add the TODO to the either the README or a seperate TODO(.md?) file @Ikornaselur?

**Comment by koddsson** [comment]
And track the issue in the issue tracker?

**Comment by ikornaselur** [comment]
That makes sense. I'll at least add it to the issue tracker.

**Pull request merged**
